services:

  robot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    network_mode: host
    ipc: host
    volumes:
      - ./dds-config.xml:/dds-config.xml
    environment:
      - ROS_DOMAIN_ID=20
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds-config.xml
    command: ros2 run demo_nodes_cpp talker
  